INSERT INTO estoque (descricao_item, categoria, unidade_medida, quantidade_atual) VALUES
    ('Acucar', 'ALIMENTO', 'kg', 0),
    ('Cafe', 'ALIMENTO', 'kg', 0),
    ('Macarrao', 'ALIMENTO', 'kg', 0),
    ('Farinha de Trigo', 'ALIMENTO', 'kg', 0),
    ('Sal', 'ALIMENTO', 'kg', 0),
    ('Leite em Po', 'ALIMENTO', 'kg', 0),
    ('Molho de Tomate', 'ALIMENTO', 'unidade', 0),
    ('Biscoito', 'ALIMENTO', 'pacote', 0),
    ('Achocolatado', 'ALIMENTO', 'kg', 0),
    ('Sardinha Enlatada', 'ALIMENTO', 'unidade', 0),
    ('Casaco/Agasalho', 'ROUPA', 'peca', 0),
    ('Calcado', 'ROUPA', 'par', 0),
    ('Roupa de Cama', 'ROUPA', 'peca', 0),
    ('Toalha', 'ROUPA', 'peca', 0),
    ('Meia', 'ROUPA', 'par', 0),
    ('Roupa Intima', 'ROUPA', 'peca', 0),
    ('Fralda Descartavel Infantil', 'ITEM_DIVERSO', 'pacote', 0),
    ('Fralda Geriatrica', 'ITEM_DIVERSO', 'pacote', 0),
    ('Produto de Higiene Pessoal', 'ITEM_DIVERSO', 'unidade', 0),
    ('Produto de Limpeza', 'ITEM_DIVERSO', 'unidade', 0),
    ('Material Escolar', 'ITEM_DIVERSO', 'unidade', 0),
    ('Livro', 'ITEM_DIVERSO', 'unidade', 0);
